#!/usr/bin/env python3

import json
import time
from pathlib import Path

import joblib
import numpy as np


# ============================================================================
# SKYGUARDIAN — REALTIME EDGE-AI ML DETECTOR
# ============================================================================

INPUT_FILE = Path("data/live/realtime_trajectory.json")
MODEL_FILE = Path("models/isolation_forest.joblib")
OUTPUT_FILE = Path("data/live/realtime_ml_results.json")

UPDATE_INTERVAL = 1.0


# ============================================================================
# FEATURES USED BY THE TRAINED ISOLATION FOREST
# ============================================================================

FEATURE_NAMES = [
    "distance_from_previous_m",
    "time_delta_s",
    "altitude_change_m",
    "speed_change_mps",
    "heading_change_deg",
    "calculated_speed_mps",
    "acceleration_mps2",
]


# ============================================================================
# READ REALTIME TRAJECTORY DATA
# ============================================================================

def read_trajectory():
    """
    Read the latest trajectory information generated by
    realtime_trajectory_tracker.py.
    """

    try:
        with open(INPUT_FILE, "r") as f:
            return json.load(f)

    except (FileNotFoundError, json.JSONDecodeError):
        return None


# ============================================================================
# LOAD ISOLATION FOREST MODEL
# ============================================================================

def load_model():
    """
    Load the Isolation Forest model.

    The saved .joblib file contains a dictionary:

        {
            "model": IsolationForest(...),
            "features": [...]
        }

    Therefore we extract the actual model from the
    dictionary before using predict().
    """

    if not MODEL_FILE.exists():
        raise FileNotFoundError(
            f"Isolation Forest model not found: {MODEL_FILE}"
        )

    print(f"Loading model: {MODEL_FILE}")

    saved_object = joblib.load(MODEL_FILE)

    # ------------------------------------------------------------
    # Model saved inside a dictionary
    # ------------------------------------------------------------

    if isinstance(saved_object, dict):

        print(
            f"Model container keys: "
            f"{list(saved_object.keys())}"
        )

        if "model" not in saved_object:
            raise ValueError(
                "Model file is a dictionary, but it does not "
                "contain a 'model' key."
            )

        model = saved_object["model"]

        # Display stored feature information if available
        if "features" in saved_object:
            print(
                f"Stored features: "
                f"{saved_object['features']}"
            )

    # ------------------------------------------------------------
    # Directly saved model
    # ------------------------------------------------------------

    else:

        model = saved_object

    # ------------------------------------------------------------
    # Validate model
    # ------------------------------------------------------------

    if not hasattr(model, "predict"):
        raise TypeError(
            "Loaded object is not a usable ML model: "
            f"{type(model)}"
        )

    print(
        f"Model type: "
        f"{type(model).__name__}"
    )

    print("Model loaded successfully.")

    return model


# ============================================================================
# CONVERT ISOLATION FOREST DECISION VALUE TO 0–100 SCORE
# ============================================================================

def calculate_ml_score(decision_value):
    """
    Convert Isolation Forest decision_function() output
    into an easy-to-understand 0–100 anomaly score.

    Important:

    This is a RELATIVE anomaly visualization score.

    It is NOT:
        - a probability
        - a confidence percentage
        - a calibrated risk score

    Isolation Forest interpretation:

        More positive decision value
            -> more normal

        More negative decision value
            -> more anomalous
    """

    score = 50.0 - (decision_value * 100.0)

    # Keep score within 0–100
    score = max(0.0, min(100.0, score))

    return score


# ============================================================================
# CLASSIFY ML RESULT
# ============================================================================

def classify_ml(prediction, ml_score):
    """
    Convert Isolation Forest prediction + score
    into a human-readable classification.

    Isolation Forest:

        prediction = 1
            -> normal

        prediction = -1
            -> anomaly
    """

    if prediction == -1:

        if ml_score >= 80:
            return "ANOMALY"

        return "MONITOR"

    if ml_score >= 70:
        return "MONITOR"

    return "NORMAL"


# ============================================================================
# EXPLAIN IMPORTANT FEATURES
# ============================================================================

def explain_features(aircraft):
    """
    Generate human-readable explanations for unusual
    trajectory characteristics.

    These explanations are NOT the Isolation Forest's
    internal explanation.

    They are simple rule-based indicators that help
    the dashboard explain why an aircraft may deserve
    attention.
    """

    explanations = []

    # ------------------------------------------------------------
    # Read feature values safely
    # ------------------------------------------------------------

    try:
        distance = abs(
            float(
                aircraft.get(
                    "distance_from_previous_m",
                    0.0
                )
            )
        )
    except (ValueError, TypeError):
        distance = 0.0

    try:
        time_delta = abs(
            float(
                aircraft.get(
                    "time_delta_s",
                    0.0
                )
            )
        )
    except (ValueError, TypeError):
        time_delta = 0.0

    try:
        altitude_change = abs(
            float(
                aircraft.get(
                    "altitude_change_m",
                    0.0
                )
            )
        )
    except (ValueError, TypeError):
        altitude_change = 0.0

    try:
        speed_change = abs(
            float(
                aircraft.get(
                    "speed_change_mps",
                    0.0
                )
            )
        )
    except (ValueError, TypeError):
        speed_change = 0.0

    try:
        heading_change = abs(
            float(
                aircraft.get(
                    "heading_change_deg",
                    0.0
                )
            )
        )
    except (ValueError, TypeError):
        heading_change = 0.0

    try:
        calculated_speed = abs(
            float(
                aircraft.get(
                    "calculated_speed_mps",
                    0.0
                )
            )
        )
    except (ValueError, TypeError):
        calculated_speed = 0.0

    try:
        acceleration = abs(
            float(
                aircraft.get(
                    "acceleration_mps2",
                    0.0
                )
            )
        )
    except (ValueError, TypeError):
        acceleration = 0.0

    # ------------------------------------------------------------
    # Rule indicators
    # ------------------------------------------------------------

    if calculated_speed > 300:
        explanations.append(
            "HIGH_CALCULATED_SPEED"
        )

    if acceleration > 10:
        explanations.append(
            "HIGH_ACCELERATION"
        )

    if speed_change > 50:
        explanations.append(
            "LARGE_SPEED_CHANGE"
        )

    if heading_change > 90:
        explanations.append(
            "LARGE_HEADING_CHANGE"
        )

    if altitude_change > 3000:
        explanations.append(
            "LARGE_ALTITUDE_CHANGE"
        )

    if time_delta > 60:
        explanations.append(
            "LARGE_TIME_GAP"
        )

    if distance > 10000:
        explanations.append(
            "LARGE_POSITION_CHANGE"
        )

    # ------------------------------------------------------------
    # No obvious rule trigger
    # ------------------------------------------------------------

    if not explanations:
        explanations.append(
            "NO_MAJOR_RULE_TRIGGER"
        )

    return explanations


# ============================================================================
# PROCESS ONE AIRCRAFT
# ============================================================================

def process_aircraft(model, aircraft):
    """
    Run the Isolation Forest on one newly updated aircraft.
    """

    # ------------------------------------------------------------
    # Only process new positions
    # ------------------------------------------------------------

    if not aircraft.get("position_updated", False):

        return {
            "ml_available": False,
            "reason": "NO_NEW_POSITION"
        }

    # ------------------------------------------------------------
    # Prepare feature vector
    # ------------------------------------------------------------

    feature_values = []

    for feature_name in FEATURE_NAMES:

        value = aircraft.get(
            feature_name,
            0.0
        )

        try:
            value = float(value)

        except (ValueError, TypeError):
            value = 0.0

        # Prevent NaN / Infinity from reaching sklearn
        if not np.isfinite(value):
            value = 0.0

        feature_values.append(value)

    # ------------------------------------------------------------
    # Create ML input matrix
    #
    # Shape:
    #
    #     1 aircraft × 7 features
    # ------------------------------------------------------------

    X = np.array(
        [feature_values],
        dtype=float
    )

    # ------------------------------------------------------------
    # Isolation Forest prediction
    # ------------------------------------------------------------

    prediction = int(
        model.predict(X)[0]
    )

    # ------------------------------------------------------------
    # Isolation Forest decision function
    # ------------------------------------------------------------

    decision_value = float(
        model.decision_function(X)[0]
    )

    # ------------------------------------------------------------
    # Convert to display score
    # ------------------------------------------------------------

    ml_score = calculate_ml_score(
        decision_value
    )

    # ------------------------------------------------------------
    # Classification
    # ------------------------------------------------------------

    classification = classify_ml(
        prediction,
        ml_score
    )

    # ------------------------------------------------------------
    # Human-readable explanations
    # ------------------------------------------------------------

    explanations = explain_features(
        aircraft
    )

    # ------------------------------------------------------------
    # Return result
    # ------------------------------------------------------------

    return {

        "ml_available": True,

        "prediction": prediction,

        "decision_function": round(
            decision_value,
            6
        ),

        "ml_anomaly_score": round(
            ml_score,
            2
        ),

        "ml_classification": classification,

        "explanations": explanations,

        "features": {
            name: round(
                value,
                6
            )
            for name, value in zip(
                FEATURE_NAMES,
                feature_values
            )
        }
    }


# ============================================================================
# MAIN LOOP
# ============================================================================

def main():

    print("=" * 72)
    print(
        "SKYGUARDIAN — REALTIME EDGE-AI ML DETECTOR"
    )
    print("=" * 72)

    print(
        f"Input : {INPUT_FILE}"
    )

    print(
        f"Model : {MODEL_FILE}"
    )

    print(
        f"Output: {OUTPUT_FILE}"
    )

    print(
        f"Update: {UPDATE_INTERVAL}s"
    )

    print("-" * 72)

    # ------------------------------------------------------------
    # Load trained model
    # ------------------------------------------------------------

    model = load_model()

    print("-" * 72)

    print(
        "Waiting for live trajectory data..."
    )

    print()

    # ------------------------------------------------------------
    # Remember the last processed timestamp
    # for every aircraft.
    #
    # This prevents running the ML model repeatedly
    # on the same trajectory observation.
    # ------------------------------------------------------------

    last_processed = {}

    # ------------------------------------------------------------
    # Continuous realtime loop
    # ------------------------------------------------------------

    while True:

        data = read_trajectory()

        if data is None:

            time.sleep(
                UPDATE_INTERVAL
            )

            continue

        results = []

        aircraft_list = data.get(
            "aircraft",
            []
        )

        # --------------------------------------------------------
        # Process every aircraft
        # --------------------------------------------------------

        for aircraft in aircraft_list:

            icao = aircraft.get(
                "icao"
            )

            if not icao:
                continue

            # ----------------------------------------------------
            # Ignore aircraft without a new position
            # ----------------------------------------------------

            if not aircraft.get(
                "position_updated",
                False
            ):
                continue

            # ----------------------------------------------------
            # Observation timestamp
            # ----------------------------------------------------

            observation_timestamp = aircraft.get(
                "timestamp"
            )

            # ----------------------------------------------------
            # Prevent duplicate processing
            # ----------------------------------------------------

            previous_timestamp = last_processed.get(
                icao
            )

            if (
                previous_timestamp is not None
                and observation_timestamp == previous_timestamp
            ):
                continue

            last_processed[
                icao
            ] = observation_timestamp

            # ----------------------------------------------------
            # Run ML detector
            # ----------------------------------------------------

            result = process_aircraft(
                model,
                aircraft
            )

            # ----------------------------------------------------
            # Add aircraft information
            # ----------------------------------------------------

            result["timestamp"] = (
                observation_timestamp
            )

            result["icao"] = icao

            result["callsign"] = (
                aircraft.get(
                    "callsign",
                    ""
                )
            )

            result["latitude"] = (
                aircraft.get(
                    "latitude"
                )
            )

            result["longitude"] = (
                aircraft.get(
                    "longitude"
                )
            )

            result["altitude_ft"] = (
                aircraft.get(
                    "altitude_ft"
                )
            )

            result["speed_kt"] = (
                aircraft.get(
                    "speed_kt"
                )
            )

            result["heading_deg"] = (
                aircraft.get(
                    "heading_deg"
                )
            )

            results.append(
                result
            )

        # --------------------------------------------------------
        # Create output document
        # --------------------------------------------------------

        output = {

            "timestamp": data.get(
                "timestamp"
            ),

            "receiver": data.get(
                "receiver"
            ),

            "aircraft_count": len(
                results
            ),

            "ml_model": {

                "type": "IsolationForest",

                "model_file": str(
                    MODEL_FILE
                ),

                "features": FEATURE_NAMES

            },

            "aircraft": results
        }

        # --------------------------------------------------------
        # Atomic JSON write
        #
        # Write to temporary file first, then replace the
        # previous output. This prevents another process
        # from reading half-written JSON.
        # --------------------------------------------------------

        temp_file = (
            OUTPUT_FILE.with_suffix(
                ".tmp"
            )
        )

        with open(
            temp_file,
            "w"
        ) as f:

            json.dump(
                output,
                f,
                indent=2
            )

        temp_file.replace(
            OUTPUT_FILE
        )

        # --------------------------------------------------------
        # Console output
        # --------------------------------------------------------

        if results:

            for result in results:

                print(
                    f"[ML] "
                    f"{result['icao']} "
                    f"{result['callsign']:<8} "
                    f"score="
                    f"{result['ml_anomaly_score']:6.2f} "
                    f"class="
                    f"{result['ml_classification']:<8} "
                    f"decision="
                    f"{result['decision_function']:.4f}"
                )

                # Print explanations when something
                # unusual is detected.

                if (
                    result["ml_classification"]
                    != "NORMAL"
                ):

                    print(
                        f"     Reasons: "
                        f"{', '.join(result['explanations'])}"
                    )

        else:

            print(
                f"\r[ML] Waiting | "
                f"Aircraft: "
                f"{len(aircraft_list):3d}",
                end="",
                flush=True
            )

        # --------------------------------------------------------
        # Wait before next cycle
        # --------------------------------------------------------

        time.sleep(
            UPDATE_INTERVAL
        )


# ============================================================================
# PROGRAM ENTRY POINT
# ============================================================================

if __name__ == "__main__":

    main()
